export const reducerCases = {
  SET_USER_INFO: 'SET_USER_INFO',
  SET_NEW_USER: 'SET_NEW_USER',
  SET_SHOW_CONTACTS_PAGE: 'SET_SHOW_CONTACTS_PAGE',
  SET_CONTACTS: 'SET_CONTACTS',
  CHANGE_CURRENT_USER: 'CHANGE_CURRENT_USER',
  SET_MESSAGES: 'SET_MESSAGES',
};
